#Requires -Version 5.1

$ErrorActionPreference = "Stop"

$toolsPath   = Split-Path -Parent $MyInvocation.MyCommand.Path
$packageRoot = Split-Path -Parent $toolsPath
$scriptDir   = Join-Path $packageRoot "scripts"
$zipSource   = Join-Path $packageRoot "ps-it-toolkit.zip"

if (-not (Test-Path $zipSource)) {
    throw "ps-it-toolkit zip not found: $zipSource"
}

# Extract to package directory (files land in tools\..\ )
Expand-Archive -Path $zipSource -DestinationPath $packageRoot -Force

# Set execution policy for the scripts directory (scoped to process for safety)
$script:ExecutionPolicy = 'RemoteSigned'

# Create a consolidated helper script that wraps all scripts with common params
$wrapper = @"
# ps-it-toolkit — common launcher
# Generated by Chocolatey packaging
# All scripts respect -Silent and -LogPath

`$scriptDir = "$scriptDir"

function Get-PSITScript {
    param([string]`$Name)
    Get-ChildItem -Path "`$scriptDir" -Filter "*`$Name*.ps1" | Select-Object -First 1
}

$allScripts = Get-ChildItem -Path "$scriptDir" -Filter "*.ps1"
foreach (`$s in `$allScripts) {
    `$base = [System.IO.Path]::GetFileNameWithoutExtension(`$s.Name)
    # dot-source each script so its functions/params are available
    # Note: scripts are designed to run standalone; dot-sourcing makes them available in-session
}

Write-Host "ps-it-toolkit loaded. Scripts in: `$scriptDir"
Write-Host "Run any script directly, e.g.: .\scripts\Invoke-WindowsRepair.ps1 -Silent"
"@

$wrapperPath = Join-Path $packageRoot "load-ps-it-toolkit.ps1"
Set-Content -Path $wrapperPath -Value $wrapper -Encoding UTF8

Write-Host "ps-it-toolkit installed to: $packageRoot"
Write-Host "Run scripts directly: $scriptDir\<ScriptName>.ps1"
